name: Windows - LiteManager

on:
   workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: Windows-latest
    timeout-minutes: 9999

    steps:
       - name: Downloading & installing Essentials
         run: 
          Invoke-WebRequest -Url "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/downloads.bat" -Outfile "Downloads.bat" 
          cmd /c Downloads.bat
          
       - name: connect to LiteManage
         run: cmd /c show.bat
       
       - name: Time counter
         run: cmd /c loop.bat
