name: Windows - LiteManager
name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Check URL accessibility
        run: |
          if (!(Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/downloads.bat" -OutFile "Downloads.bat")) {
            Write-Error "Failed to download Downloads.bat"
            exit 1
          }

      - name: Downloading & installing Essentials
        run: |
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time counter
        run: cmd /c loop.bat
